name: 'Artifact'
uses: actions/upload-artifact@v2
on:
  push:
    branches: [master]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
with:
  name: 'Test artifact'
  path: /testing
