name: 'artifacts'
on:
  push:
    branches: [master]
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    # The type of runner that the job will run on
    steps:
      - run: pwd
      - run: mkdir -p ${{ github.workspace }}/artifact

      - run: cd ${{ github.workspace }} && ls -la

      - run: pwd

      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ${{ github.workspace }}/artifact/

      - run: echo $PATH
