name: 'artifacts'
on:
  push:
    branches: [master]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    steps:
      - uses: actions/upload-artifact@v2
        run:
          name: my-artifact
          path: path/to/artifact/ # or path/to/artifact

