name: Upload a Build Artifact
  - uses: actions/upload-artifact@v2
  with:
    # Artifact name
    name: Test artifact
    # A file, directory or wildcard pattern that describes what to upload
    path: testing
