name: 'artifacts'
on:
  push:
    branches: [master]
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    # The type of runner that the job will run on
    steps:
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./testing # or path/to/artifact

